name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.2.2', '8.4.4', '8.6.5', '8.8.4', '8.10.7', '9.0.2', '9.2.7', '9.4.4']
    name: Build with GHC ${{ matrix.ghc }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}

    - run: cabal v2-update
    - run: cabal v2-freeze
    - uses: actions/cache@v2
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-

    - run: cabal v2-build
    - run: cabal v2-test
    - run: cabal v2-sdist
